### ISSUE TITLE
File closing bug

### ISSUE THREAD

**Issue by WilliamJamieson** [Goddard-Fortran-Ecosystem/yaFyaml#22]
If one loads a file using a FilesStream into the parser, the file is left open by the parser and so it cannot be reopened by fortran. The iterator example ([line](https://github.com/Goddard-Fortran-Ecosystem/yaFyaml/blob/ff15d81ce6cbea8f17bbc02ca1c39509f7910b3f/Examples/Iterators/iterator.F90#L26)) exhibits this issue; however, the program does not attempt to re-access the `iterator.yaml` file meaning no error actually occurs.

I suggest that it be made possible to pass a string containing a file name directly to a parser, which would handle opening and closing the string internally.

**Comment by tclune** [comment]
The "fix" will be to overload the interface to allow a filename to be specified.   The filestream interface cannot/should not close the file, as files are permitted to have multiple yaml documents.

**Comment by tclune** [comment]
Fixed.
