### ISSUE TITLE
Compiler with Intel 18.1

### ISSUE THREAD

**Issue by LiamBindle** [Goddard-Fortran-Ecosystem/yaFyaml#27]
Hi all,

We had a user report a compiler error in yaFyaml, specifically

```
/scratch/cnt0022/lat0005/tsivlidou/Code.GCHP/src/yaFyaml/src/Parser.F90(106): error #7497: The variable must be type compatible with the expression and of the same rank. [TOKEN]
token = lexr%get_token()
```

they are using Intel 18.1 (or possiblly 18.0.1? I don't see a 18.1 release on Intel's website). Any chance you know what this error is?

Thanks,
Liam

**Comment by LiamBindle** [comment]
@tclune Do you have any ideas by any chance?

**Comment by tclune** [comment]
This looks a bit familiar, and is likely a compiler bug.   A simple thing to try would be to replace the line with
```
allocate(token, source=lexr%get_token())
```
Unlikely to fix the issue, but it is so easy to try.

I strongly recommend that they at least get up to 18.0.5, but I could try to check to make sure that works first. (99% certain that it does.)

If they really really need this to work with the older compiler, the whole `get_token()` aspect could be changed from a function to a subroutine.     That generally fixes that kind of thing in the compiler.   It's tedious and not my preferred style.    I'd be happy to give instructions if someone wanted to make the attempt.  If it works (and also works with the newer compilers!) I could accept it as a PR.

**Comment by LiamBindle** [comment]
Thanks Tom. I'll recommend they upgrade their compiler, and if that isn't possible, then I'll help them explore fixes. Thanks for your help.
