### ISSUE TITLE
How to test if a key is present when the value is itself another configuration

### ISSUE THREAD

**Issue by bena-nasa** [Goddard-Fortran-Ecosystem/yaFyaml#8]
```
U:
   file_var: U
   file_template: fileU
V:
   file_var: V
   file_template: fileV
```
I have this simple yaml file. At the top level, the keys are U and V.
Once I load the yaml file, how do I test if the key is present, where the value of the key is itself another configuration, and then return a new configuration type if it is. I could not figure out how to do this in a way that would compile.
For example I first did this:
```
type(configuration) :: rule,config
character(len=:), allocatable :: file_var
! load config
rule = config%at('U')
call rule%get(file_var,'file_var',default='not_found',is_present=is_present)
```
This builds and works as I expect.
But what is what I want to "get" is not an integer, real, character but itself another configuration. It was not clear from the examples and looking at the source code how to do this or get something to compile.
The source code suggests for example that the "at" function of configuration has an "is_present" option but that would not compile if I added that.

**Comment by tclune** [comment]
It is possible that an is_present optional argument should be added to the get_config_at_selector.

Currently the approach is that you always get a Config, but if the selector does not exist, then the Config has a null pointer inside.   Not quite so convenient in your case, but worked well enough in some other use cases.

Feel free to do a PR or noodge.

**Comment by tclune** [comment]
Oh - a bit more.  It does not set the pointer no "null()".   It sets the pointer to a global "None" object.   The config can then be tested with the is_none() method:

```f90
call config%get(rule, 'U')
if (.not. rule%is_none())
   ...
```

**Comment by bena-nasa** [comment]
This seems to work, calling config%is_none(). That was the secret I was missing.
